// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD_GmsFNPCA1GFadsVVJwu4ktET-U8V1s',
    appId: '1:1018837083142:web:4a93eb28657876adb30f87',
    messagingSenderId: '1018837083142',
    projectId: 'inspexion-ai',
    authDomain: 'inspexion-ai.firebaseapp.com',
    storageBucket: 'inspexion-ai.firebasestorage.app',
    measurementId: 'G-DL22PZ9653',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX2d7S88kSBAjbN43H4GN5qh677Ac_gss',
    appId: '1:1018837083142:android:5fa64bd6f91a83d5b30f87',
    messagingSenderId: '1018837083142',
    projectId: 'inspexion-ai',
    storageBucket: 'inspexion-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4mf6y6dR6iG379WM5-AU9N08EKLZ0MM',
    appId: '1:1018837083142:ios:41213e4a4641ea8bb30f87',
    messagingSenderId: '1018837083142',
    projectId: 'inspexion-ai',
    storageBucket: 'inspexion-ai.firebasestorage.app',
    androidClientId: '1018837083142-eng7rkbbojn3cmrgeadqp61nrdgr7t5l.apps.googleusercontent.com',
    iosClientId: '1018837083142-l0obet1llit9j69hu6s19f1mfr9aht36.apps.googleusercontent.com',
    iosBundleId: 'com.yourcompany.inspexionai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj4mf6y6dR6iG379WM5-AU9N08EKLZ0MM',
    appId: '1:1018837083142:ios:55024ce3dcf752d1b30f87',
    messagingSenderId: '1018837083142',
    projectId: 'inspexion-ai',
    storageBucket: 'inspexion-ai.firebasestorage.app',
    androidClientId: '1018837083142-eng7rkbbojn3cmrgeadqp61nrdgr7t5l.apps.googleusercontent.com',
    iosClientId: '1018837083142-0kklhtj7arvpfovjmknnov7m59d1q0np.apps.googleusercontent.com',
    iosBundleId: 'com.example.inspexionAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD_GmsFNPCA1GFadsVVJwu4ktET-U8V1s',
    appId: '1:1018837083142:web:6e7fba07490643ceb30f87',
    messagingSenderId: '1018837083142',
    projectId: 'inspexion-ai',
    authDomain: 'inspexion-ai.firebaseapp.com',
    storageBucket: 'inspexion-ai.firebasestorage.app',
    measurementId: 'G-S4T75BXMYG',
  );
}
